export const GET_PRODUCT_SUBSCRIPTION_FROM_CONTRACT_REQUEST =
    'marketplace/product/GET_PRODUCT_SUSBCRIPTION_FROM_CONTRACT_REQUEST'
export const GET_PRODUCT_SUBSCRIPTION_FROM_CONTRACT_SUCCESS =
    'marketplace/product/GET_PRODUCT_SUSBCRIPTION_FROM_CONTRACT_SUCCESS'
export const GET_PRODUCT_SUBSCRIPTION_FROM_CONTRACT_FAILURE =
    'marketplace/product/GET_PRODUCT_SUSBCRIPTION_FROM_CONTRACT_FAILURE'
