#
# https://dependabot.com/docs/config-file/validator/
#
---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
    assignees:
      - DaisyDomergue
    labels:
      - ci
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
      include: scope
    assignees:
      - tumppi
      - mondoreale
    labels:
      - build
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "08:00"
      timezone: Europe/Helsinki
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    assignees:
      - tumppi
      - mondoreale
    labels:
      - build

