// @flow

export const INTEGRATION_KEYS_REQUEST: string = 'shared/integrationKey/INTEGRATION_KEYS_REQUEST'
export const INTEGRATION_KEYS_SUCCESS: string = 'shared/integrationKey/INTEGRATION_KEYS_SUCCESS'
export const INTEGRATION_KEYS_FAILURE: string = 'shared/integrationKey/INTEGRATION_KEYS_FAILURE'

export const CREATE_INTEGRATION_KEY_REQUEST = 'shared/integrationKey/CREATE_INTEGRATION_KEY_REQUEST'
export const CREATE_INTEGRATION_KEY_SUCCESS = 'shared/integrationKey/CREATE_INTEGRATION_KEY_SUCCESS'
export const CREATE_INTEGRATION_KEY_FAILURE = 'shared/integrationKey/CREATE_INTEGRATION_KEY_FAILURE'

export const DELETE_INTEGRATION_KEY_REQUEST = 'shared/integrationKey/DELETE_INTEGRATION_KEY_REQUEST'
export const DELETE_INTEGRATION_KEY_SUCCESS = 'shared/integrationKey/DELETE_INTEGRATION_KEY_SUCCESS'
export const DELETE_INTEGRATION_KEY_FAILURE = 'shared/integrationKey/DELETE_INTEGRATION_KEY_FAILURE'

export const CREATE_IDENTITY_REQUEST = 'shared/integrationKey/CREATE_IDENTITY_REQUEST'
export const CREATE_IDENTITY_SUCCESS = 'shared/integrationKey/CREATE_IDENTITY_SUCCESS'
export const CREATE_IDENTITY_FAILURE = 'shared/integrationKey/CREATE_IDENTITY_FAILURE'

export const EDIT_INTEGRATION_KEY_REQUEST = 'shared/integrationKey/EDIT_INTEGRATION_KEY_REQUEST'
export const EDIT_INTEGRATION_KEY_SUCCESS = 'shared/integrationKey/EDIT_INTEGRATION_KEY_SUCCESS'
export const EDIT_INTEGRATION_KEY_FAILURE = 'shared/integrationKey/EDIT_INTEGRATION_KEY_FAILURE'

export const SET_BALANCE = 'shared/integrationKey/SET_BALANCE'
