// flow-typed signature: ced69f4e87cfea24f25384e0803d1520
// flow-typed version: <<STUB>>/css-mqpacker_v^6.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-mqpacker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-mqpacker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-mqpacker/bin/mqpacker' {
  declare module.exports: any;
}

declare module 'css-mqpacker/test/css-mqpacker_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-mqpacker/bin/mqpacker.js' {
  declare module.exports: $Exports<'css-mqpacker/bin/mqpacker'>;
}
declare module 'css-mqpacker/index' {
  declare module.exports: $Exports<'css-mqpacker'>;
}
declare module 'css-mqpacker/index.js' {
  declare module.exports: $Exports<'css-mqpacker'>;
}
declare module 'css-mqpacker/test/css-mqpacker_test.js' {
  declare module.exports: $Exports<'css-mqpacker/test/css-mqpacker_test'>;
}
