// flow-typed signature: dfc602a4c74aeea0ffa37384c9dd0e11
// flow-typed version: <<STUB>>/flowtype-loader_v^0.2.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flowtype-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flowtype-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flowtype-loader/lib/flowResult' {
  declare module.exports: any;
}

declare module 'flowtype-loader/lib/flowStatus' {
  declare module.exports: any;
}

declare module 'flowtype-loader/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flowtype-loader/index' {
  declare module.exports: $Exports<'flowtype-loader'>;
}
declare module 'flowtype-loader/index.js' {
  declare module.exports: $Exports<'flowtype-loader'>;
}
declare module 'flowtype-loader/lib/flowResult.js' {
  declare module.exports: $Exports<'flowtype-loader/lib/flowResult'>;
}
declare module 'flowtype-loader/lib/flowStatus.js' {
  declare module.exports: $Exports<'flowtype-loader/lib/flowStatus'>;
}
declare module 'flowtype-loader/plugin.js' {
  declare module.exports: $Exports<'flowtype-loader/plugin'>;
}
