// flow-typed signature: 3ac6e5731dc95465a0c2b5c2e2fdaef9
// flow-typed version: <<STUB>>/html-webpack-react-root-plugin_v^0.9.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-react-root-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-react-root-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-webpack-react-root-plugin/lib/constants' {
  declare module.exports: any;
}

declare module 'html-webpack-react-root-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'html-webpack-react-root-plugin/test/plugin_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-webpack-react-root-plugin/index' {
  declare module.exports: $Exports<'html-webpack-react-root-plugin'>;
}
declare module 'html-webpack-react-root-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-react-root-plugin'>;
}
declare module 'html-webpack-react-root-plugin/lib/constants.js' {
  declare module.exports: $Exports<'html-webpack-react-root-plugin/lib/constants'>;
}
declare module 'html-webpack-react-root-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'html-webpack-react-root-plugin/lib/plugin'>;
}
declare module 'html-webpack-react-root-plugin/test/plugin_test.js' {
  declare module.exports: $Exports<'html-webpack-react-root-plugin/test/plugin_test'>;
}
