// flow-typed signature: b4c1c98e063ee374434fbd894684b155
// flow-typed version: <<STUB>>/postcss-extend_v^1.0.5/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-extend/index' {
  declare module.exports: $Exports<'postcss-extend'>;
}
declare module 'postcss-extend/index.js' {
  declare module.exports: $Exports<'postcss-extend'>;
}
