export const GET_MY_PURCHASES_REQUEST = 'marketplace/myPurchaseList/GET_MY_PURCHASES_REQUEST'
export const GET_MY_PURCHASES_SUCCESS = 'marketplace/myPurchaseList/GET_MY_PURCHASES_SUCCESS'
export const GET_MY_PURCHASES_FAILURE = 'marketplace/myPurchaseList/GET_MY_PURCHASES_FAILURE'
export const UPDATE_FILTER = 'marketplace/myPurchaseList/UPDATE_FILTER'
export const UPDATE_RESULTS = 'marketplace/myPurchaseList/UPDATE_RESULTS'
