/* eslint-disable max-len */
import moduleDescription from './HTTPRequest-1001.md'

export default {
    id: 1001,
    name: 'HTTP Request',
    path: 'Integrations',
    help: {
        outputNames: [
            'errors',
            'data',
            'status code',
            'ping(ms)',
            'headers',
        ],
        inputs: {
            trigger: 'Send request when input arrives',
            body: 'Request body',
        },
        inputNames: [
            'body',
            'trigger',
        ],
        params: {
            verb: 'HTTP verb (e.g. GET, POST)',
            URL: 'URL to send the request to',
            params: 'Query parameters added to URL (?name=value)',
            headers: 'HTTP Request headers',
        },
        outputs: {
            errors: 'Empty list if all went correctly',
            data: 'Server response payload',
            'status code': '200..299 means all went correctly',
            'ping(ms)': 'Round-trip response time in milliseconds',
            headers: 'HTTP Response headers',
        },
        paramNames: [
            'verb',
            'URL',
            'params',
            'headers',
        ],
        helpText: moduleDescription,
    },
    inputs: [
        {
            id: 'ep_bbscQj-gSjCApedQP_U1aw',
            name: 'body',
            longName: 'HTTP Request.body',
            type: 'Object',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Object',
            ],
            requiresConnection: true,
        },
    ],
    outputs: [
        {
            id: 'ep_7BDe2g53Tma3N6Wmh-TmuA',
            name: 'errors',
            longName: 'HTTP Request.errors',
            type: 'List',
            connected: false,
            canConnect: true,
            export: false,
        },
        {
            id: 'ep_LPnGHtLFS0CRwiJi7cS5mA',
            name: 'data',
            longName: 'HTTP Request.data',
            type: 'Object',
            connected: false,
            canConnect: true,
            export: false,
        },
        {
            id: 'ep_3TMGCAVvQHScFbC-T75B-w',
            name: 'statusCode',
            longName: 'HTTP Request.statusCode',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_g0NNEhxpRZOXUfF9Uxc4aQ',
            name: 'roundtripMillis',
            longName: 'HTTP Request.roundtripMillis',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_hkkjmXvWQRenkRa0nlcAiA',
            name: 'headers',
            longName: 'HTTP Request.headers',
            type: 'Map',
            connected: false,
            canConnect: true,
            export: false,
        },
    ],
    params: [
        {
            id: 'ep_BtXIBV0lTlufUG6Ld_AoZA',
            name: 'verb',
            longName: 'HTTP Request.verb',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: 'POST',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            possibleValues: [
                {
                    name: 'GET',
                    value: 'GET',
                },
                {
                    name: 'POST',
                    value: 'POST',
                },
                {
                    name: 'PUT',
                    value: 'PUT',
                },
                {
                    name: 'DELETE',
                    value: 'DELETE',
                },
                {
                    name: 'PATCH',
                    value: 'PATCH',
                },
            ],
            defaultValue: 'POST',
            updateOnChange: true,
            isTextArea: false,
        },
        {
            id: 'ep_MDJo_r0FTciPUEL1wrRQHA',
            name: 'URL',
            longName: 'HTTP Request.URL',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: '',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: '',
            isTextArea: false,
        },
        {
            id: 'ep_kU3O9fAdT8m0RNBxFxGUpw',
            name: 'params',
            longName: 'HTTP Request.params',
            type: 'Map',
            connected: false,
            canConnect: true,
            export: false,
            value: {},
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Map',
            ],
            requiresConnection: false,
            defaultValue: {},
        },
        {
            id: 'ep_hUosdTZRRP6sjXIVFGB8MQ',
            name: 'headers',
            longName: 'HTTP Request.headers',
            type: 'Map',
            connected: false,
            canConnect: true,
            export: false,
            value: {},
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Map',
            ],
            requiresConnection: false,
            defaultValue: {},
        },
    ],
}
