export const GET_PRODUCTS_REQUEST = 'marketplace/productList/GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'marketplace/productList/GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'marketplace/productList/GET_PRODUCTS_FAILURE'
export const UPDATE_FILTER = 'marketplace/productList/UPDATE_FILTER'
export const CLEAR_FILTERS = 'marketplace/productList/CLEAR_FILTERS'
export const CLEAR_PRODUCT_LIST = 'marketplace/productList/CLEAR_PRODUCT_LIST'
export const UPDATE_PROJECTS_AUTHOR_FILTER = 'marketplace/productList/UPDATE_PROJECTS_AUTHOR_FILTER'
