# Dev2 (docker)

[dev2.client]
dataUnionJoinServerUrl = ":5555"
graphUrl = ":8800/subgraphs/name/streamr-dev/network-subgraphs"

# Mumbai

[mumbai.client]
dataUnionJoinServerUrl = "https://join.dataunions.org/"
graphUrl = "https://api.thegraph.com/subgraphs/name/samt1803/network-subgraphs"
