[dev0]
dockerHost = "localhost"

[dev1]
dockerHost = "localhost"

[dev2]
dataUnionJoinServerUrl = ":5555"
dockerHost = "localhost"
marketplaceChains = ['dev2']
networkSubgraphUrl = ":8800/subgraphs/name/streamr-dev/network-subgraphs"
streamIndexerUrl = ":4001/api"

[[dev2.storageNodes]]
name = "Local (broker-node-storage-1)"
address = "0xde1112f631486CfC759A50196853011528bC5FA0"

[[dev2.dataunionGraphNames]]
chainId = 31337
name = "streamr-dev/dataunion"

[amoy]
dataUnionJoinServerUrl = "https://join.dataunions.org/"
marketplaceChains = ['amoy']

[[amoy.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[[amoy.dataunionGraphNames]]
chainId = 80002
name = "samt1803/dataunion-subgraphs"

[polygon]
marketplaceChains = ['gnosis', 'polygon']
networkSubgraphUrl = "https://gateway-arbitrum.network.thegraph.com/api/8bcbd55cdd1369cadb0bb813d9817776/subgraphs/id/EGWFdhhiWypDuz22Uy7b3F69E9MEkyfU9iAQMttkH5Rj"
streamIndexerUrl = "https://stream-metrics.streamr.network/api"

[[polygon.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[[polygon.storageNodes]]
name = "LogStore Decentralized Storage"
address = "0x17f98084757a75add72bf6c5b5a6f69008c28a57"
thirdPartyLink = "https://docs.usher.so/logstore/network/quick-start/using-streamr-sdk"

[[polygon.dataunionGraphNames]]
chainId = 100
name = "dataunions/data-unions-gnosis"

[[polygon.dataunionGraphNames]]
chainId = 137
name = "dataunions/data-unions-polygon"
