[dev2]
dockerHost = "localhost"
networkSubgraphUrl = ":8800/subgraphs/name/streamr-dev/network-subgraphs"
streamIndexerUrl = ":4001/api"

[dev2.client]
dataUnionJoinServerUrl = ":5555"
networkSubgraphUrl = ":8800/subgraphs/name/streamr-dev/network-subgraphs"


[mumbai]
networkSubgraphUrl = "https://api.thegraph.com/subgraphs/name/samt1803/network-subgraphs"
streamIndexerUrl = "https://stream-metrics-staging.streamr.network/api"

[mumbai.client]
dataUnionJoinServerUrl = "https://join.dataunions.org/"
networkSubgraphUrl = "https://api.thegraph.com/subgraphs/name/samt1803/network-subgraphs"
