[dev2]
dockerHost = "localhost"
marketplaceChains = ['dev2']
networkSubgraphUrl = ":8800/subgraphs/name/streamr-dev/network-subgraphs"
streamIndexerUrl = ":4001/api"

[dev2.client]
dataUnionJoinServerUrl = ":5555"
networkSubgraphUrl = ":8800/subgraphs/name/streamr-dev/network-subgraphs"

[[dev2.storageNodes]]
name = "Local (broker-node-storage-1)"
address = "0xde1112f631486CfC759A50196853011528bC5FA0"

[[dev2.dataunionGraphNames]]
chainId = 31337
name = "streamr-dev/dataunion"

[polygonAmoy]
marketplaceChains = ['polygonAmoy']
networkSubgraphUrl = "https://api.thegraph.com/subgraphs/name/samt1803/network-subgraphs"

[polygonAmoy.client]
dataUnionJoinServerUrl = "https://join.dataunions.org/"
networkSubgraphUrl = "https://api.thegraph.com/subgraphs/name/samt1803/network-subgraphs"

[[polygonAmoy.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[[polygonAmoy.dataunionGraphNames]]
chainId = 80002
name = "samt1803/dataunion-subgraphs"

[polygon]
enforceLocalNetworkSubgraphUrl = true
marketplaceChains = ['gnosis', 'polygon']
networkSubgraphUrl = "https://gateway-arbitrum.network.thegraph.com/api/8bcbd55cdd1369cadb0bb813d9817776/subgraphs/id/EGWFdhhiWypDuz22Uy7b3F69E9MEkyfU9iAQMttkH5Rj"
streamIndexerUrl = "https://stream-metrics.streamr.network/api"

[[polygon.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[[polygon.dataunionGraphNames]]
chainId = 100
name = "dataunions/data-unions-gnosis"

[[polygon.dataunionGraphNames]]
chainId = 137
name = "dataunions/data-unions-polygon"
