[development]
availableChains = ['dev2', 'polygon', 'mumbai']
platformOriginUrl = ""
streamrUrl = ""

[mumbai]
availableChains = ['mumbai', 'polygon']
platformOriginUrl = "https://staging.streamr.network"
streamrUrl = "https://staging.streamr.network"

[production]
availableChains = ['polygon', 'mumbai']
