[development]
availableChains = ['dev2', 'polygon', 'polygonAmoy']
platformOriginUrl = ""
streamrUrl = ""

[polygonAmoy]
availableChains = ['polygonAmoy', 'polygon']
platformOriginUrl = "https://staging.streamr.network"
streamrUrl = "https://staging.streamr.network"

[production]
availableChains = ['polygon', 'polygonAmoy']
