[core]
uniswapAdaptorContractAddress = "0xE4eA76e830a659282368cA2e7E4d18C4AE52D8B3"
web3TransactionConfirmationBlocks = 1
availableChains = ['mumbai']
defaultChain = 'mumbai'

[[core.dataunionGraphNames]]
chainId = 80001
name = "samt1803/dataunion-subgraphs"

[[core.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"
