[core]
uniswapAdaptorContractAddress = "0xBe99DB4Ea1964ea9A9E80de41517901Da6ef9307"
web3TransactionConfirmationBlocks = 1
availableChains = ['polygon', 'mumbai']
defaultChain = 'polygon'
marketplaceChains = ['gnosis', 'polygon']
theGraphUrl = "https://api.thegraph.com"
streamIndexerUrl = "https://stream-metrics.streamr.network/api"

[[core.dataunionGraphNames]]
chainId = 100
name = "dataunions/data-unions-gnosis"

[[core.dataunionGraphNames]]
chainId = 137
name = "dataunions/data-unions-polygon"

[[core.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[core.ipfs]
projectId = "2KjYUpR265h6R5M5njkSue5RGm7"
apiSecretKey = "c39492773b28820c8b3654178bf26946"
ipfsUploadEndpoint = "https://ipfs.infura.io:5001/api/v0/add"
ipfsGatewayUrl = "https://streamr-hub.infura-ipfs.io/ipfs/"
