[core]
uniswapAdaptorContractAddress = "0xBe99DB4Ea1964ea9A9E80de41517901Da6ef9307"
web3TransactionConfirmationBlocks = 1
availableChains = ['polygon', 'mumbai']
marketplaceChains = ['gnosis', 'polygon']

[[core.dataunionGraphNames]]
chainId = 100
name = "dataunions/data-unions-gnosis"

[[core.dataunionGraphNames]]
chainId = 137
name = "dataunions/data-unions-polygon"

[[core.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"
