[core]
dataUnionPublishMemberLimit = 1
platformOriginUrl = "https://streamr.network"
streamrUrl = "https://streamr.network"
uniswapAdaptorContractAddress = "0xBe99DB4Ea1964ea9A9E80de41517901Da6ef9307"
web3TransactionConfirmationBlocks = 1
marketplaceChains = ['gnosis', 'polygon']
dataunionChains = ['gnosis', 'polygon']
streamChains = ['polygon']
theGraphUrl = "https://api.thegraph.com"
mainnetInfuraUrl = "https://mainnet.infura.io/v3/17c3985baecb4c4d94a1edc2c4d23206"
theHubGraphName = "INSERT HUB SUBGRAPH NAME WHEN DEPLOYED"

[[core.marketplaceContractCreationBlocks]]
chainId = 1
blockNumber = 13575716

[[core.marketplaceContractCreationBlocks]]
chainId = 100
blockNumber = 23758654

[[core.marketplaceContractCreationBlocks]]
chainId = 137
blockNumber = 32026284

[[core.dataunionGraphNames]]
chainId = 100
name = "dataunions/data-unions-gnosis"

[[core.dataunionGraphNames]]
chainId = 137
name = "dataunions/data-unions-polygon"

[[core.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[client.mainchain]
dataTokenAddress = "0x8f693ca8D21b157107184d29D398A8D082b38b76"

[client.mainchain.rpc]
chainId = 1

[[client.mainchain.rpc.rpcs]]
url = "https://mainnet.infura.io/v3/17c3985baecb4c4d94a1edc2c4d23206"

[client.sidechain]
dataTokenAddress = "0xE4a2620edE1058D61BEe5F45F6414314fdf10548"
