[core]
dataUnionPublishMemberLimit = 1
platformOriginUrl = "https://streamr.network"
streamrUrl = "https://streamr.network"
uniswapAdaptorContractAddress = "0xBe99DB4Ea1964ea9A9E80de41517901Da6ef9307"
web3TransactionConfirmationBlocks = 1
marketplaceChains = ['ethereum', 'gnosis', 'polygon']
dataunionChains = ['gnosis', 'polygon']
streamChains = ['polygon']

[[client.mainchain.rpc.rpcs]]
url = "https://mainnet.infura.io/v3/17c3985baecb4c4d94a1edc2c4d23206"

[[core.storageNodes]]
name = "Streamr Germany"
address = "0x31546eEA76F2B2b3C5cC06B1c93601dc35c9D916"

[client]
restUrl = "https://streamr.network/api/v2"
streamrNodeAddress = "0xf3E5A65851C3779f468c9EcB32E6f25D9D68601a"

[client.mainchain]
chainId = 1
dataTokenAddress = "0x8f693ca8D21b157107184d29D398A8D082b38b76"

[client.sidechain]
dataTokenAddress = "0xE4a2620edE1058D61BEe5F45F6414314fdf10548"
