#!/usr/bin/env bash
set -e
echo "Config Env Variables:"
echo $NODE_ENV
echo $PORT
echo $VERSION
echo $SENTRY_ENVIRONMENT
echo $BUNDLE_ANALYSIS
echo $REST_URL
echo $STREAMR_WS_URL
echo $PLATFORM_ORIGIN_URL
echo $STREAMR_URL
echo $PLATFORM_PUBLIC_PATH
echo $GOOGLE_ANALYTICS_ID
echo $STORYBOOK_BASE_PATH
echo $MARKETPLACE_CONTRACT_ADDRESS
echo $DATA_TOKEN_CONTRACT_ADDRESS
echo $DAI_TOKEN_CONTRACT_ADDRESS
echo $UNISWAP_ADAPTOR_CONTRACT_ADDRESS
echo $MAINNET_CHAIN_ID
echo $MAINNET_HTTP_PROVIDER
echo $SENTRY_DSN
echo $SENTRY_INDEXER_DSN
echo $LOGROCKET_SLUG
npm run build-index
npm run build
