// @flow
export const GET_CATEGORIES_REQUEST: string = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS: string = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE: string = 'GET_CATEGORIES_FAILURE'

export const GET_PRODUCTS_BY_CATEGORY_REQUEST: string = 'GET_PRODUCTS_BY_CATEGORY_REQUEST'
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS: string = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS'
export const GET_PRODUCTS_BY_CATEGORY_FAILURE: string = 'GET_PRODUCTS_BY_CATEGORY_FAILURE'
