/* eslint-disable max-len */
import moduleDescription from './Chart-67.md'

export default {
    id: 67,
    name: 'Chart',
    path: 'Visualizations',
    help: {
        params: {},
        paramNames: [],
        inputs: {},
        inputNames: [],
        outputs: {},
        outputNames: [],
        helpText: moduleDescription,
    },
    inputs: [
        {
            id: 'ep_R9VfzVpQR-ekuDx5rz-L8Q',
            name: 'in1',
            longName: 'Chart.in1',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_KWnvLAlASkWDf8bdlXqWRg',
            name: 'in2',
            longName: 'Chart.in2',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_BruyU7ymSum3RiqN2ohuXA',
            name: 'in3',
            longName: 'Chart.in3',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_F68Zw4quT9mhi_Hpai3GYg',
            name: 'in4',
            longName: 'Chart.in4',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_9-hkRFmeRLqaiuEbwoBSGw',
            name: 'in5',
            longName: 'Chart.in5',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_aJqvzSFtTBGU-VOwJ55kLA',
            name: 'in6',
            longName: 'Chart.in6',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_4K25eFFhQb6g8ExbCvSU_Q',
            name: 'in7',
            longName: 'Chart.in7',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_yBlOrNANRlC2MC_3UywTTg',
            name: 'in8',
            longName: 'Chart.in8',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_2FQ_x0fmQ42arkh6tR61Vw',
            name: 'in9',
            longName: 'Chart.in9',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
        {
            id: 'ep_eoVqN9l7SeGFAkHHnndgLg',
            name: 'in10',
            longName: 'Chart.in10',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: false,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            canHaveInitialValue: false,
            yAxis: 0,
        },
    ],
    outputs: [],
    params: [],
}
