/* eslint-disable max-len */
import moduleDescription from './FlexBarify-158.md'

export default {
    id: 158,
    name: 'FlexBarify',
    path: 'Time Series: Utils',
    help: {
        outputNames: [
            'open',
            'high',
            'low',
            'close',
            'avg',
        ],
        inputs: {
            value: 'Value to be sampled into the bar',
            valueLength: "Length of each event, contributes to <span class='highlight'>barLength**",
        },
        helpText: moduleDescription,
        inputNames: [
            'valueLength',
            'value',
        ],
        params: {
            barLength: "Length of each bar (in <span class='highlight'>valueLength** units)",
        },
        outputs: {
            open: 'Value at start of period',
            high: 'Maximum value during period',
            avg: "Average of values received during the period, weighted by <span class='highlight'>valueLength**",
            low: 'Minimum value during period',
            close: 'Value at end of period (the most recent value)',
        },
        paramNames: [
            'barLength',
        ],
    },
    inputs: [
        {
            id: 'ep_uDM7_axUTuShaPYvWN_7AA',
            name: 'valueLength',
            longName: 'FlexBarify.valueLength',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
        {
            id: 'ep_WxtR76cJTh2iGNA2cnu47w',
            name: 'value',
            longName: 'FlexBarify.value',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
    ],
    outputs: [
        {
            id: 'ep_SY2IJHmzSsmrwAO7BtN2BA',
            name: 'open',
            longName: 'FlexBarify.open',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_mqIBzepHTOqy51aYbh7W3Q',
            name: 'high',
            longName: 'FlexBarify.high',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_IyTp_WCMTrOMjgVHazzyPA',
            name: 'low',
            longName: 'FlexBarify.low',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_4TBkxtxESsiokGoIc1v-rg',
            name: 'close',
            longName: 'FlexBarify.close',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_wKPnWGPFTZaEIPH_z6WcNw',
            name: 'avg',
            longName: 'FlexBarify.avg',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_MSVwx-xHSwqC2iVu7QdYPA',
            name: 'sum',
            longName: 'FlexBarify.sum',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
    ],
    params: [
        {
            id: 'ep_THURNtNnSa2etbpqDAlOZA',
            name: 'barLength',
            longName: 'FlexBarify.barLength',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 5000,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 5000,
        },
    ],
}
