/* eslint-disable max-len */
import moduleDescription from './Range-545.md'

export default {
    id: 545,
    name: 'Range',
    path: 'List',
    help: {
        params: {
            from: 'start of sequence; included in sequence.',
            step: 'step size to add/subtract; sign is ignored; an empty sequence is produced if set to 0',
            to: 'upper bound of sequence; not necessarily included in sequence',
        },
        paramNames: [
            'from',
            'step',
            'to',
        ],
        inputs: {},
        inputNames: [],
        outputs: {
            out: 'the generated sequence',
        },
        outputNames: [
            'out',
        ],
        helpText: moduleDescription,
    },
    inputs: [],
    outputs: [
        {
            id: 'ep_I4cmvlvVTW-nRcNpr6Wi2A',
            name: 'out',
            longName: 'Range.out',
            type: 'List',
            connected: false,
            canConnect: true,
            export: false,
            value: [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
                81,
                82,
                83,
                84,
                85,
                86,
                87,
                88,
                89,
                90,
                91,
                92,
                93,
                94,
                95,
                96,
                97,
                98,
                99,
                100,
            ],
        },
    ],
    params: [
        {
            id: 'ep_4idShBGhS6eQ54C73GFn3w',
            name: 'from',
            longName: 'Range.from',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 0,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 0,
        },
        {
            id: 'ep_oaqYy8oPQxWGw7Xhwr18og',
            name: 'step',
            longName: 'Range.step',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 1,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 1,
        },
        {
            id: 'ep_GKeEZ9ONT4-uUxwllO5bbg',
            name: 'to',
            longName: 'Range.to',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 100,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 100,
        },
    ],
}
