/* eslint-disable max-len */
import moduleDescription from './SpearmansRankCorrelation-55.md'

export default {
    id: 55,
    name: 'SpearmansRankCorrelation',
    path: 'Time Series: Statistics',
    help: {
        outputNames: [],
        inputs: {},
        helpText: moduleDescription,
        inputNames: [],
        params: {},
        outputs: {},
        paramNames: [],
    },
    inputs: [
        {
            id: 'ep_8KqQcM5fSYuVf5pt_Uvp2A',
            name: 'inX',
            longName: 'SpearmansRankCorrelation.inX',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
        {
            id: 'ep_YIWU_tqXSFiSQSwA4jj3PA',
            name: 'inY',
            longName: 'SpearmansRankCorrelation.inY',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
    ],
    outputs: [
        {
            id: 'ep_x6iIujhBSLSmPSSIan68Hw',
            name: 'corr',
            longName: 'SpearmansRankCorrelation.corr',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
    ],
    params: [
        {
            id: 'ep_cNCvZj6kTMSSwYzn_h42yw',
            name: 'windowLength',
            longName: 'SpearmansRankCorrelation.windowLength',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 0,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 0,
        },
        {
            id: 'ep_mQFnfaewRhOxDjyoftHQLQ',
            name: 'windowType',
            longName: 'SpearmansRankCorrelation.windowType',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: 'events',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: 'events',
            isTextArea: false,
            possibleValues: [
                {
                    name: 'events',
                    value: 'EVENTS',
                },
                {
                    name: 'seconds',
                    value: 'SECONDS',
                },
                {
                    name: 'minutes',
                    value: 'MINUTES',
                },
                {
                    name: 'hours',
                    value: 'HOURS',
                },
                {
                    name: 'days',
                    value: 'DAYS',
                },
            ],
        },
        {
            id: 'ep_llWg3BFyRTO71FFO5aSAWA',
            name: 'minSamples',
            longName: 'SpearmansRankCorrelation.minSamples',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 2,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 2,
        },
    ],
}
