/* eslint-disable max-len */
import moduleDescription from './SQL-1010.md'

export default {
    id: 1010,
    name: 'SQL',
    path: 'Integrations',
    help: {
        params: {
            engine: 'Database engine, e.g. MySQL',
            host: 'Database server to connect',
            database: 'Name of the database',
            username: 'Login username',
            password: 'Login password',
        },
        paramNames: [
            'engine',
            'host',
            'database',
            'username',
            'password',
        ],
        inputs: {
            sql: 'SQL command to be executed',
        },
        inputNames: [
            'sql',
        ],
        outputs: {
            errors: 'List of error strings',
            result: 'List of rows returned by the database',
        },
        outputNames: [
            'errors',
            'result',
        ],
        helpText: moduleDescription,
    },
    inputs: [
        {
            id: 'ep_ElZO_LOHQyWadgdmMZYCVw',
            name: 'sql',
            longName: 'SQL.sql',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
    ],
    outputs: [
        {
            id: 'ep_UEptiPl9Q76n8YRMr8yLiw',
            name: 'errors',
            longName: 'SQL.errors',
            type: 'List',
            connected: false,
            canConnect: true,
            export: false,
        },
        {
            id: 'ep_ZrKyrsvXRsijY3tdx6ll3g',
            name: 'result',
            longName: 'SQL.result',
            type: 'List',
            connected: false,
            canConnect: true,
            export: false,
        },
    ],
    params: [
        {
            id: 'ep_URkiQydHQPGbSo8YVLZOMw',
            name: 'engine',
            longName: 'SQL.engine',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: 'MySQL',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: 'MySQL',
            isTextArea: false,
            possibleValues: [
                {
                    name: 'MySQL',
                    value: 'MySQL',
                },
                {
                    name: 'PostgreSQL',
                    value: 'PostgreSQL',
                },
            ],
        },
        {
            id: 'ep_hz--De4eSeWO19-YgYOEjw',
            name: 'host',
            longName: 'SQL.host',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: '',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: '',
            isTextArea: false,
        },
        {
            id: 'ep_A_LnqfhCRv-edhhtZ2kOeA',
            name: 'database',
            longName: 'SQL.database',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: '',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: '',
            isTextArea: false,
        },
        {
            id: 'ep_TC_5rrIaQ8-6Om7uVmjh_Q',
            name: 'username',
            longName: 'SQL.username',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: '',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: '',
            isTextArea: false,
        },
        {
            id: 'ep_y1yx42uRT2Ovj4wO-AHm1A',
            name: 'password',
            longName: 'SQL.password',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: '',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: '',
            isTextArea: false,
        },
    ],
}
