/* eslint-disable max-len */
import moduleDescription from './UnivariateLinearRegression-51.md'

export default {
    id: 51,
    name: 'UnivariateLinearRegression',
    path: 'Time Series: Statistics',
    help: {
        outputNames: [
            'slope',
            'intercept',
            'error',
            'R^2',
        ],
        inputs: {
            inX: 'Input X values',
            inY: 'Input Y values',
        },
        helpText: moduleDescription,
        inputNames: [
            'inX',
            'inY',
        ],
        params: {
            windowLength: 'Length of the sliding window as number of samples',
        },
        outputs: {
            error: 'Mean square error (MSE) of the fit',
            intercept: 'Intercept of the linear fit',
            slope: 'Slope of the linear fit',
            'R^2': 'R-squared value of the fit',
        },
        paramNames: [
            'windowLength',
        ],
    },
    inputs: [
        {
            id: 'ep_xcsM9XCNTQ6DctZ7WFrgig',
            name: 'inX',
            longName: 'UnivariateLinearRegression.inX',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
        {
            id: 'ep_AxJEyzXJSkuT8Qm8-fzLOA',
            name: 'inY',
            longName: 'UnivariateLinearRegression.inY',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            drivingInput: true,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: true,
            canHaveInitialValue: true,
            initialValue: null,
        },
    ],
    outputs: [
        {
            id: 'ep_0LEai2_4SD-vdNv51jaeVg',
            name: 'slope',
            longName: 'UnivariateLinearRegression.slope',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_vIb5ef4sROWFu17o6-0mvw',
            name: 'intercept',
            longName: 'UnivariateLinearRegression.intercept',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_gWOBNLV1TT66iZwwca_QBA',
            name: 'error',
            longName: 'UnivariateLinearRegression.error',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
        {
            id: 'ep_fGuEWp96SCmUSatYuOsUyA',
            name: 'R^2',
            longName: 'UnivariateLinearRegression.R^2',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            noRepeat: false,
            canBeNoRepeat: true,
        },
    ],
    params: [
        {
            id: 'ep__oJlFdPvRlyvPN3kS-xwCw',
            name: 'windowLength',
            longName: 'UnivariateLinearRegression.windowLength',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 0,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 0,
        },
        {
            id: 'ep_XpQQwMClTdK2bYHEVrCqrQ',
            name: 'windowType',
            longName: 'UnivariateLinearRegression.windowType',
            type: 'String',
            connected: false,
            canConnect: true,
            export: false,
            value: 'events',
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'String',
            ],
            requiresConnection: false,
            defaultValue: 'events',
            isTextArea: false,
            possibleValues: [
                {
                    name: 'events',
                    value: 'EVENTS',
                },
                {
                    name: 'seconds',
                    value: 'SECONDS',
                },
                {
                    name: 'minutes',
                    value: 'MINUTES',
                },
                {
                    name: 'hours',
                    value: 'HOURS',
                },
                {
                    name: 'days',
                    value: 'DAYS',
                },
            ],
        },
        {
            id: 'ep_YJRAtEC2S_eTAvjnhz3xDA',
            name: 'minSamples',
            longName: 'UnivariateLinearRegression.minSamples',
            type: 'Double',
            connected: false,
            canConnect: true,
            export: false,
            value: 0,
            drivingInput: false,
            canToggleDrivingInput: true,
            acceptedTypes: [
                'Double',
            ],
            requiresConnection: false,
            defaultValue: 0,
        },
    ],
}
