name: Lint, build and test
on: [push]

defaults:
  run:
    working-directory: app

jobs:  
  test:
    name: Run eslint, stylelint and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run ESlint
        run: npm run eslint
      - name: Run Stylelint
        run: npm run stylelint
      - name: Build
        run: npm run build --if-present
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.2
        with:
          services-to-start: "mysql redis engine-and-editor cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 nginx smtp"
      - name: Run tests
        run: npm run test
