name: Eslint and test
on: [push]

defaults:
  run:
    working-directory: app

jobs:
  test:
    name: Run eslint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run eslint
      - run: npm run build --if-present
      - run: npm run test
